spring:
  application:
    name: auth-service

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET}
    expiration:
      access: ${JWT_EXPIRATION_ACCESS}
      refresh: ${JWT_EXPIRATION_REFRESH}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  elasticsearch:
    uris: ${ELASTICSEARCH_URL}

rabbitmq:
  queue:
    user:
      created: ${RABBITMQ_QUEUE_USER_CREATED}
      updated: ${RABBITMQ_QUEUE_USER_UPDATED}
  exchange:
    user: ${RABBITMQ_EXCHANGE_USER}

security:
  pepper: my-pepper-key-hash2

server:
  port: 8081