spring:

  application:
    name: gateway

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      server:
        web flux:
          global:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "https://app.ogocx.com"
                  - "http://localhost:3000"
                allowed-methods: [ GET, POST, PUT, PATCH, DELETE,]
                allowed-headers: "*"
                exposed-headers: [ X-Correlation-Id ]
                allow-credentials: true
                max-age: 3600
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service
                    fallbackUri: forward:/fallback/users
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                    key-resolver: "#{@ipKeyResolver}"
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: auth-service
                    fallbackUri: forward:/fallback/auth
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@ipKeyResolver}"

gateway:
  public-routes:
    - /auth/sign-in
    - /auth/refresh

jwt:
  secret: ${JWT_SECRET}

resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        slidingWindowSize: 10
        failureRateThreshold: 20
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
      user-service:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED

  timelimiter:
    instances:
      auth-service:
        timeoutDuration: 3s
      user-service:
        timeoutDuration: 5s

  bulkhead:
    instances:
      auth-service:
        maxConcurrentCalls: 20
        maxWaitDuration: 100ms
      user-service:
        maxConcurrentCalls: 40
        maxWaitDuration: 100ms

server:
  port: 8082